Admin user panel + Own user panel
GijsPampiermole/Actievadis pull request #67
Opened 2022-10-14 09:45 UTC by keygun-development

2022-10-17 18:12 UTC, BenBerkenbosch requested changes
419 PAGE Expired Error. After this is solved, everything is deemed to work.

2022-10-17 18:14 UTC, keygun-development commented
@BenBerkenbosch can you specify which page you're trying to access? Like just send the url to me

2022-10-18 07:04 UTC, BenBerkenbosch commented
Everything works as expected. Really well-done job at the coding. The middleware is a great way to authorize everything.

2022-10-18 07:04 UTC, BenBerkenbosch approved these changes

2022-10-18 07:04 UTC, merged